#server:
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#
#spring:
#  application:
#    name: eurka-server

# 安全

spring:
  security:
    user:
      name: wumu
      password: wumu
  application:
    name: discovery-cluster
---
spring:
  profiles: discovery1
server:
  port: 8761
eureka:
  instance:
    hostname: host2
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://host1/eureka

---
spring:
  profiles: discovery2
server:
  port: 8762
eureka:
  instance:
    hostname: host1
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default-zone: http://host2/eureka

